name: Testing stuff

on:
  push:
    branches:
      - master

jobs:
  a_test_job:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: gihub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        run: echo "$COMMITS"
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ join(github.event.commits.*.message) }}
        run: contains(COMMIT_MESSAGES, join)
